#include "../config.h"
#include "../../include/pokemon.h"
// #include "../global.h"
#ifdef TRAINERS_WITH_EVS
/*
trainers_with_evs_table.h
	defining the EV/IV/ability/ball type to be assigned to trainer pokemon
*/

#define TERA_TYPE_RANDOM_ALL 0xFE
#define TERA_TYPE_RANDOM     0xFF
#define DONT_TERA            TYPE_BLANK

const struct TrainersWithEvs gTrainersWithEvsSpreads[] =
{
	[0] = {0}, //Empty Spread
	[1] =
	{ //Physical Sweeper: Power Based
		.nature = NATURE_ADAMANT,
		.ivs = 31,
		.hpEv = 6,
		.atkEv = 252,
		.spdEv = 252,
		.ball =  BALL_TYPE_DUSK_BALL,                     
		//   TRAINER_EV_CLASS_BALL,
		.ability = Ability_Random_1_2,
		.teraType = TYPE_FIRE,
				// .teraType = TERA_TYPE_RANDOM,
	},
	[2] = //256
	{ //Physical Sweeper: Speed Based
		// .nature = NATURE_JOLLY,
		// .ivs = 31,
		// .hpEv = 6,
		// .atkEv = 252,
		// .spdEv = 252,
		// .ball = TRAINER_EV_CLASS_BALL,
		// .ability = Ability_Random_1_2,
		// .teraType = TERA_TYPE_RANDOM,

		//Modest. 19 ivs, 30 evs. Ability Hidden. Tera Ghost. Lea and Jed's Ninetales on Route 16.
		.nature = NATURE_MODEST,
		.ivs = 19,
		.hpEv = 30,
		.atkEv = 30,
		.defEv = 30,
		.spAtkEv = 30,
		.spDefEv = 30,
		.spdEv = 30,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TYPE_GHOST,
	},
	[3] = //257
	{ // { //Special Sweeper: Power Based
	// 	.nature = NATURE_MODEST,
	// 	.ivs = 31,
	// 	.hpEv = 6,
	// 	.spdEv = 252,
	// 	.spAtkEv = 252,
	// 	.ball = TRAINER_EV_CLASS_BALL,
	// 	.ability = Ability_Random_1_2,
	// 	.teraType = TERA_TYPE_RANDOM,

	//Adamant. 19 ivs, 30 evs. Axle's Gyarados on Route 19.
		.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 30,
		.atkEv = 30,
		.defEv = 30,
		.spAtkEv = 30,
		.spDefEv = 30,
		.spdEv = 30,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[4] = //258
	{ // { //Special Sweeper: Speed Based
	// 	.nature = NATURE_TIMID,
	// 	.ivs = 31,
	// 	.hpEv = 6,
	// 	.spdEv = 252,
	// 	.spAtkEv = 252,
	// 	.ball = TRAINER_EV_CLASS_BALL,
	// 	.ability = Ability_Random_1_2,
	// 	.teraType = TERA_TYPE_RANDOM,

	.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 30,
		.atkEv = 30,
		.defEv = 30,
		.spAtkEv = 30,
		.spDefEv = 30,
		.spdEv = 30,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TYPE_GHOST,
	},
	[5] = //259
	{ //Bulky Physical Attacker 
		// .nature = NATURE_ADAMANT,
		// .ivs = 31,
		// .hpEv = 252,
		// .atkEv = 252,
		// .spdEv = 6,
		// .ball = TRAINER_EV_CLASS_BALL,
		// .ability = Ability_Random_1_2,
		// .teraType = TERA_TYPE_RANDOM,

        .nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 30,
		.atkEv = 30,
		.defEv = 30,
		.spAtkEv = 30,
		.spDefEv = 30,
		.spdEv = 30,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TYPE_ELECTRIC,
	},
	[6] = //260
	{ //Bulky Physical Attacker 
		// .nature = NATURE_ADAMANT,
		// .ivs = 31,
		// .hpEv = 6,
		// .atkEv = 252,
		// .defEv = 252,
		// .ball = TRAINER_EV_CLASS_BALL,
		// .ability = Ability_Random_1_2,
		// .teraType = TERA_TYPE_RANDOM,

		.nature = NATURE_MODEST,
		.ivs = 19,
		.hpEv = 30,
		.atkEv = 30,
		.defEv = 30,
		.spAtkEv = 30,
		.spDefEv = 30,
		.spdEv = 30,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TYPE_FAIRY,
	},
	[7] = //261
	{ //Bulky Physical Attacker 
		// .nature = NATURE_ADAMANT,
		// .ivs = 31,
		// .hpEv = 6,
		// .atkEv = 252,
		// .spDefEv = 252,
		// .ball = TRAINER_EV_CLASS_BALL,
		// .ability = Ability_Random_1_2,
		// .teraType = TERA_TYPE_RANDOM,

		.nature = NATURE_SERIOUS,
		.ivs = 19,
		.hpEv = 30,
		.atkEv = 30,
		.defEv = 30,
		.spAtkEv = 30,
		.spDefEv = 30,
		.spdEv = 30,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[8] = //262
	{ //Bulky Special Attacker
		// .nature = NATURE_MODEST,
		// .ivs = 31,
		// .hpEv = 252,
		// .spdEv = 6,
		// .spAtkEv = 252,
		// .ball = TRAINER_EV_CLASS_BALL,
		// .ability = Ability_Random_1_2,
		// .teraType = TERA_TYPE_RANDOM,

		.nature = NATURE_SERIOUS,
		.ivs = 19,
		.hpEv = 30,
		.atkEv = 30,
		.defEv = 30,
		.spAtkEv = 30,
		.spDefEv = 30,
		.spdEv = 30,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TYPE_DARK,
	},
	[9] = //263
	{ //Bulky Special Attacker
		// .nature = NATURE_MODEST,
		// .ivs = 31,
		// .hpEv = 6,
		// .defEv = 252,
		// .spAtkEv = 252,
		// .ball = TRAINER_EV_CLASS_BALL,
		// .ability = Ability_Random_1_2,
		// .teraType = TERA_TYPE_RANDOM,

		//Adamant. 19 ivs, 30 evs. Tera Water. Tisha's Kingler on Bond Bridge.
		.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 30,
		.atkEv = 30,
		.defEv = 30,
		.spAtkEv = 30,
		.spDefEv = 30,
		.spdEv = 30,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TYPE_WATER,
	},
	[10] = //264
	{ //Bulky Special Attacker
		// .nature = NATURE_MODEST,
		// .ivs = 31,
		// .hpEv = 6,
		// .spAtkEv = 252,
		// .spDefEv = 252,
		// .ball = TRAINER_EV_CLASS_BALL,
		// .ability = Ability_Random_1_2,
		// .teraType = TERA_TYPE_RANDOM,

		//Adamant. 19 ivs, 50 evs. Tera Poison. Ray and Tyra's Nidoking in Victory Road.
		.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 50,
		.atkEv = 50,
		.defEv = 50,
		.spAtkEv = 50,
		.spDefEv = 50,
		.spdEv = 50,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TYPE_POISON,
	},
	[11] = //265
	{ //Physical Wall
		// .nature = NATURE_BOLD,
		// .ivs = 31,
		// .hpEv = 252,
		// .defEv = 252,
		// .spDefEv = 4,
		// .ball = TRAINER_EV_CLASS_BALL,
		// .ability = Ability_Random_1_2,
		// .teraType = TERA_TYPE_RANDOM,

		//Modest. 19 ivs, 50 evs. Tera Flying. Ray and Tyra's Nidoqueen in Victory Road.
		.nature = NATURE_MODEST,
		.ivs = 19,
		.hpEv = 50,
		.atkEv = 50,
		.defEv = 50,
		.spAtkEv = 50,
		.spDefEv = 50,
		.spdEv = 50,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TYPE_FLYING,
	},
	[12] = //266
	{ //Physical Wall
		// .nature = NATURE_IMPISH,
		// .ivs = 31,
		// .hpEv = 252,
		// .defEv = 252,
		// .spDefEv = 4,
		// .ball = TRAINER_EV_CLASS_BALL,
		// .ability = Ability_Random_1_2,
		// .teraType = TERA_TYPE_RANDOM,

		.nature = NATURE_SERIOUS,
		.ivs = 17,
		.hpEv = 45,
		.atkEv = 45,
		.defEv = 45,
		.spAtkEv = 45,
		.spDefEv = 45,
		.spdEv = 45,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[13] = //267
	{ //Special Wall: Less Attack
		// .nature = NATURE_CALM,
		// .ivs = 31,
		// .hpEv = 252,
		// .defEv = 4,
		// .spDefEv = 252,
		// .ball = TRAINER_EV_CLASS_BALL,
		// .ability = Ability_Random_1_2,
		// .teraType = TERA_TYPE_RANDOM,

		.nature = NATURE_SERIOUS,
		.ivs = 17,
		.hpEv = 45,
		.atkEv = 45,
		.defEv = 45,
		.spAtkEv = 45,
		.spDefEv = 45,
		.spdEv = 45,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[14] = //268
	{ //Special Wall: Less Special Attack
		// .nature = NATURE_CAREFUL,
		// .ivs = 31,
		// .hpEv = 252,
		// .defEv = 4,
		// .spDefEv = 252,
		// .ball = TRAINER_EV_CLASS_BALL,
		// .ability = Ability_Random_1_2,
		// .teraType = TERA_TYPE_RANDOM,

		.nature = NATURE_SERIOUS,
		.ivs = 17,
		.hpEv = 45,
		.atkEv = 45,
		.defEv = 45,
		.spAtkEv = 45,
		.spDefEv = 45,
		.spdEv = 45,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[15] = //269
	{ //Mixed Attacker: Attack Based, Less Defense
		// .nature = NATURE_LONELY,
		// .ivs = 31,
		// .atkEv = 128,
		// .spdEv = 252,
		// .spAtkEv = 128,
		// .ball = TRAINER_EV_CLASS_BALL,
		// .ability = Ability_Random_1_2,
		// .teraType = TERA_TYPE_RANDOM,

		//Adamant. Ability Hidden, Tera Normal. Dawson's Lickilicky on Victory Road.
		.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 50,
		.atkEv = 50,
		.defEv = 50,
		.spAtkEv = 50,
		.spDefEv = 50,
		.spdEv = 50,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TYPE_NORMAL,
	},
	[16] = //270
	{ //Mixed Attacker: Attack Based, Less Sp. Defense
		// .nature = NATURE_NAUGHTY,
		// .ivs = 31,
		// .atkEv = 128,
		// .spdEv = 252,
		// .spAtkEv = 128,
		// .ball = TRAINER_EV_CLASS_BALL,
		// .ability = Ability_Random_1_2,
		// .teraType = TERA_TYPE_RANDOM,

		//Adamant. Ability Hidden, Nelson's Aerodactyl on Victory Road.
		.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 50,
		.atkEv = 50,
		.defEv = 50,
		.spAtkEv = 50,
		.spDefEv = 50,
		.spdEv = 50,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[17] =
	{ //Mixed Attacker: Sp. Attack Based, Less Defense
		.nature = NATURE_MILD,
		.ivs = 31,
		.atkEv = 128,
		.spdEv = 252,
		.spAtkEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Random_1_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[18] =
	{ //Mixed Attacker: Sp. Attack Based, Less Sp. Defense
		.nature = NATURE_RASH,
		.ivs = 31,
		.atkEv = 128,
		.spdEv = 252,
		.spAtkEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Random_1_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[19] =
	{ //Mixed Attacker: Speed Based, Less Defense
		.nature = NATURE_HASTY,
		.ivs = 31,
		.atkEv = 128,
		.spdEv = 252,
		.spAtkEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Random_1_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[20] =
	{ //Mixed Attacker: Speed Based, Less Sp. Defense
		.nature = NATURE_NAIVE,
		.ivs = 31,
		.atkEv = 128,
		.spdEv = 252,
		.spAtkEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Random_1_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[21] =
	{ //Mixed Wall: Defense Based, Less Attack
		.nature = NATURE_BOLD,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 128,
		.spDefEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Random_1_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[22] =
	{ //Mixed Wall: Defense Based, Less Sp. Attack
		.nature = NATURE_IMPISH,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 128,
		.spDefEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Random_1_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[23] =
	{ //Mixed Wall: Sp. Defense Based, Less Attack
		.nature = NATURE_CALM,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 128,
		.spDefEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Random_1_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[24] =
	{ //Mixed Wall: Sp. Defense Based, Less Sp. Attack
		.nature = NATURE_CAREFUL,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 128,
		.spDefEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Random_1_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[25] =
	{ //Fast Wall: HP Based, Less Attack
		.nature = NATURE_TIMID,
		.ivs = 31,
		.hpEv = 252,
		.spdEv = 252,
		.spAtkEv = 4,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Random_1_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[26] =
	{ //Fast Wall: HP Based, Less Sp. Attack
		.nature = NATURE_JOLLY,
		.ivs = 31,
		.hpEv = 252,
		.atkEv = 4,
		.spdEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Random_1_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[27] =
	{ //Fast Wall: Defense Based, Less Attack
		.nature = NATURE_TIMID,
		.ivs = 31,
		.hpEv = 4,
		.defEv = 252,
		.spdEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Random_1_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[28] =
	{ //Fast Wall: Defense Based, Less Sp. Attack
		.nature = NATURE_JOLLY,
		.ivs = 31,
		.hpEv = 4,
		.defEv = 252,
		.spdEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Random_1_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[29] =
	{ //Fast Wall: Sp. Defense Based, Less Attack
		.nature = NATURE_TIMID,
		.ivs = 31,
		.hpEv = 4,
		.spdEv = 252,
		.spDefEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Random_1_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[30] =
	{ //Fast Wall: Sp. Defense Based, Less Sp. Attack
		.nature = NATURE_JOLLY,
		.ivs = 31,
		.hpEv = 4,
		.spdEv = 252,
		.spDefEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Random_1_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[31] =
	{ //Physical Sweeper: Power Based - Ability_1
		.nature = NATURE_ADAMANT,
		.ivs = 31,
		.hpEv = 6,
		.atkEv = 252,
		.spdEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[32] =
	{ //Physical Sweeper: Speed Based - Ability_1
		.nature = NATURE_JOLLY,
		.ivs = 31,
		.hpEv = 6,
		.atkEv = 252,
		.spdEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[33] =
	{ //Special Sweeper: Power Based - Ability_1
		.nature = NATURE_MODEST,
		.ivs = 31,
		.hpEv = 6,
		.spdEv = 252,
		.spAtkEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[34] =
	{ //Special Sweeper: Speed Based - Ability_1
		.nature = NATURE_TIMID,
		.ivs = 31,
		.hpEv = 6,
		.spdEv = 252,
		.spAtkEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[35] =
	{ //Bulky Physical Attacker - Ability_1
		.nature = NATURE_ADAMANT,
		.ivs = 31,
		.hpEv = 252,
		.atkEv = 252,
		.spdEv = 6,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[36] =
	{ //Bulky Physical Attacker - Ability_1
		.nature = NATURE_ADAMANT,
		.ivs = 31,
		.hpEv = 6,
		.atkEv = 252,
		.defEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[37] =
	{ //Bulky Physical Attacker - Ability_1
		.nature = NATURE_ADAMANT,
		.ivs = 31,
		.hpEv = 6,
		.atkEv = 252,
		.spDefEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[38] =
	{ //Bulky Special Attacker - Ability_1
		.nature = NATURE_MODEST,
		.ivs = 31,
		.hpEv = 252,
		.spdEv = 6,
		.spAtkEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[39] =
	{ //Bulky Special Attacker - Ability_1
		.nature = NATURE_MODEST,
		.ivs = 31,
		.hpEv = 6,
		.defEv = 252,
		.spAtkEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[40] =
	{ //Bulky Special Attacker - Ability_1
		.nature = NATURE_MODEST,
		.ivs = 31,
		.hpEv = 6,
		.spAtkEv = 252,
		.spDefEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[41] =
	{ //Physical Wall - Ability_1
		.nature = NATURE_BOLD,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[42] =
	{ //Physical Wall - Ability_1
		.nature = NATURE_IMPISH,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[43] =
	{ //Special Wall - Ability_1
		.nature = NATURE_CALM,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[44] =
	{ //Special Wall - Ability_1
		.nature = NATURE_CAREFUL,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[45] =
	{ //Mixed Attacker: Attack Based, Less Defense - Ability_1
		.nature = NATURE_LONELY,
		.ivs = 31,
		.atkEv = 128,
		.spdEv = 252,
		.spAtkEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[46] =
	{ //Mixed Attacker: Attack Based, Less Sp. Defense - Ability_1
		.nature = NATURE_NAUGHTY,
		.ivs = 31,
		.atkEv = 128,
		.spdEv = 252,
		.spAtkEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[47] =
	{ //Mixed Attacker: Sp. Attack Based, Less Defense - Ability_1
		.nature = NATURE_MILD,
		.ivs = 31,
		.atkEv = 128,
		.spdEv = 252,
		.spAtkEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[48] =
	{ //Mixed Attacker: Sp. Attack Based, Less Sp. Defense - Ability_1
		.nature = NATURE_RASH,
		.ivs = 31,
		.atkEv = 128,
		.spdEv = 252,
		.spAtkEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[49] =
	{ //Mixed Attacker: Speed Based, Less Defense - Ability_1
		.nature = NATURE_HASTY,
		.ivs = 31,
		.atkEv = 128,
		.spdEv = 252,
		.spAtkEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[50] =
	{ //Mixed Attacker: Speed Based, Less Sp. Defense - Ability_1
		.nature = NATURE_NAIVE,
		.ivs = 31,
		.atkEv = 128,
		.spdEv = 252,
		.spAtkEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[51] =
	{ //Mixed Wall: Defense Based, Less Attack - Ability_1
		.nature = NATURE_BOLD,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 128,
		.spDefEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[52] =
	{ //Mixed Wall: Defense Based, Less Sp. Attack - Ability_1
		.nature = NATURE_IMPISH,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 128,
		.spDefEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[53] =
	{ //Mixed Wall: Sp. Defense Based, Less Attack - Ability_1
		.nature = NATURE_CALM,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 128,
		.spDefEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[54] =
	{ //Mixed Wall: Sp. Defense Based, Less Sp. Attack - Ability_1
		.nature = NATURE_CAREFUL,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 128,
		.spDefEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[55] =
	{ //Fast Wall: HP Based, Less Attack - Ability_1
		.nature = NATURE_TIMID,
		.ivs = 31,
		.hpEv = 252,
		.spdEv = 252,
		.spAtkEv = 4,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[56] =
	{ //Fast Wall: HP Based, Less Sp. Attack - Ability_1
		.nature = NATURE_JOLLY,
		.ivs = 31,
		.hpEv = 252,
		.atkEv = 4,
		.spdEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[57] =
	{ //Fast Wall: Defense Based, Less Attack - Ability_1
		.nature = NATURE_TIMID,
		.ivs = 31,
		.hpEv = 4,
		.defEv = 252,
		.spdEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[58] =
	{ //Fast Wall: Defense Based, Less Sp. Attack - Ability_1
		.nature = NATURE_JOLLY,
		.ivs = 31,
		.hpEv = 4,
		.defEv = 252,
		.spdEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[59] =
	{ //Fast Wall: Sp. Defense Based, Less Attack - Ability_1
		.nature = NATURE_TIMID,
		.ivs = 31,
		.hpEv = 4,
		.spdEv = 252,
		.spDefEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[60] =
	{ //Fast Wall: Sp. Defense Based, Less Sp. Attack - Ability_1
		.nature = NATURE_JOLLY,
		.ivs = 31,
		.hpEv = 4,
		.spdEv = 252,
		.spDefEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TERA_TYPE_RANDOM,
	},
	[61] =
	{ //Physical Sweeper: Power Based - Ability_2
		.nature = NATURE_ADAMANT,
		.ivs = 31,
		.hpEv = 6,
		.atkEv = 252,
		.spdEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[62] =
	{ //Physical Sweeper: Speed Based - Ability_2
		.nature = NATURE_JOLLY,
		.ivs = 31,
		.hpEv = 6,
		.atkEv = 252,
		.spdEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[63] =
	{ //Special Sweeper: Power Based - Ability_2
		.nature = NATURE_MODEST,
		.ivs = 31,
		.hpEv = 6,
		.spdEv = 252,
		.spAtkEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[64] =
	{ //Special Sweeper: Speed Based - Ability_2
		.nature = NATURE_TIMID,
		.ivs = 31,
		.hpEv = 6,
		.spdEv = 252,
		.spAtkEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[65] =
	{ //Bulky Physical Attacker - Ability_2
		.nature = NATURE_ADAMANT,
		.ivs = 31,
		.hpEv = 252,
		.atkEv = 252,
		.spdEv = 6,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[66] =
	{ //Bulky Physical Attacker - Ability_2
		.nature = NATURE_ADAMANT,
		.ivs = 31,
		.hpEv = 6,
		.atkEv = 252,
		.defEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[67] =
	{ //Bulky Physical Attacker - Ability_2
		.nature = NATURE_ADAMANT,
		.ivs = 31,
		.hpEv = 6,
		.atkEv = 252,
		.spDefEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[68] =
	{ //Bulky Special Attacker - Ability_2
		.nature = NATURE_MODEST,
		.ivs = 31,
		.hpEv = 252,
		.spdEv = 6,
		.spAtkEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[69] =
	{ //Bulky Special Attacker - Ability_2
		.nature = NATURE_MODEST,
		.ivs = 31,
		.hpEv = 6,
		.defEv = 252,
		.spAtkEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[70] =
	{ //Bulky Special Attacker - Ability_2
		.nature = NATURE_MODEST,
		.ivs = 31,
		.hpEv = 6,
		.spAtkEv = 252,
		.spDefEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[71] =
	{ //Physical Wall - Ability_2
		.nature = NATURE_BOLD,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[72] =
	{ //Physical Wall - Ability_2
		.nature = NATURE_IMPISH,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[73] =
	{ //Special Wall - Ability_2
		.nature = NATURE_CALM,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[74] =
	{ //Special Wall - Ability_2
		.nature = NATURE_CAREFUL,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[75] =
	{ //Mixed Attacker: Attack Based, Less Defense - Ability_2
		.nature = NATURE_LONELY,
		.ivs = 31,
		.atkEv = 128,
		.spdEv = 252,
		.spAtkEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[76] =
	{ //Mixed Attacker: Attack Based, Less Sp. Defense - Ability_2
		.nature = NATURE_NAUGHTY,
		.ivs = 31,
		.atkEv = 128,
		.spdEv = 252,
		.spAtkEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[77] =
	{ //Mixed Attacker: Sp. Attack Based, Less Defense - Ability_2
		.nature = NATURE_MILD,
		.ivs = 31,
		.atkEv = 128,
		.spdEv = 252,
		.spAtkEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[78] =
	{ //Mixed Attacker: Sp. Attack Based, Less Sp. Defense - Ability_2
		.nature = NATURE_RASH,
		.ivs = 31,
		.atkEv = 128,
		.spdEv = 252,
		.spAtkEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[79] =
	{ //Mixed Attacker: Speed Based, Less Defense - Ability_2
		.nature = NATURE_HASTY,
		.ivs = 31,
		.atkEv = 128,
		.spdEv = 252,
		.spAtkEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[80] =
	{ //Mixed Attacker: Speed Based, Less Sp. Defense - Ability_2
		.nature = NATURE_NAIVE,
		.ivs = 31,
		.atkEv = 128,
		.spdEv = 252,
		.spAtkEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[81] =
	{ //Mixed Wall: Defense Based, Less Attack - Ability_2
		.nature = NATURE_BOLD,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 128,
		.spDefEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[82] =
	{ //Mixed Wall: Defense Based, Less Sp. Attack - Ability_2
		.nature = NATURE_IMPISH,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 128,
		.spDefEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[83] =
	{ //Mixed Wall: Sp. Defense Based, Less Attack - Ability_2
		.nature = NATURE_CALM,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 128,
		.spDefEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[84] =
	{ //Mixed Wall: Sp. Defense Based, Less Sp. Attack - Ability_2
		.nature = NATURE_CAREFUL,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 128,
		.spDefEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[85] =
	{ //Fast Wall: HP Based, Less Attack - Ability_2
		.nature = NATURE_TIMID,
		.ivs = 31,
		.hpEv = 252,
		.spdEv = 252,
		.spAtkEv = 4,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[86] =
	{ //Fast Wall: HP Based, Less Sp. Attack - Ability_2
		.nature = NATURE_JOLLY,
		.ivs = 31,
		.hpEv = 252,
		.atkEv = 4,
		.spdEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[87] =
	{ //Fast Wall: Defense Based, Less Attack - Ability_2
		.nature = NATURE_TIMID,
		.ivs = 31,
		.hpEv = 4,
		.defEv = 252,
		.spdEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[88] =
	{ //Fast Wall: Defense Based, Less Sp. Attack - Ability_2
		.nature = NATURE_JOLLY,
		.ivs = 31,
		.hpEv = 4,
		.defEv = 252,
		.spdEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[89] =
	{ //Fast Wall: Sp. Defense Based, Less Attack - Ability_2
		.nature = NATURE_TIMID,
		.ivs = 31,
		.hpEv = 4,
		.spdEv = 252,
		.spDefEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[90] =
	{ //Fast Wall: Sp. Defense Based, Less Sp. Attack - Ability_2
		.nature = NATURE_JOLLY,
		.ivs = 31,
		.hpEv = 4,
		.spdEv = 252,
		.spDefEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TERA_TYPE_RANDOM,
	},
	[91] =
	{ //Physical Sweeper: Power Based - Ability_Hidden
		.nature = NATURE_ADAMANT,
		.ivs = 31,
		.hpEv = 6,
		.atkEv = 252,
		.spdEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[92] =
	{ //Physical Sweeper: Speed Based - Ability_Hidden
		.nature = NATURE_JOLLY,
		.ivs = 31,
		.hpEv = 6,
		.atkEv = 252,
		.spdEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[93] =
	{ //Special Sweeper: Power Based - Ability_Hidden
		.nature = NATURE_MODEST,
		.ivs = 31,
		.hpEv = 6,
		.spdEv = 252,
		.spAtkEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[94] =
	{ //Special Sweeper: Speed Based - Ability_Hidden
		.nature = NATURE_TIMID,
		.ivs = 31,
		.hpEv = 6,
		.spdEv = 252,
		.spAtkEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[95] =
	{ //Bulky Physical Attacker - Ability_Hidden
		.nature = NATURE_ADAMANT,
		.ivs = 31,
		.hpEv = 252,
		.atkEv = 252,
		.spdEv = 6,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[96] =
	{ //Bulky Physical Attacker - Ability_Hidden
		.nature = NATURE_ADAMANT,
		.ivs = 31,
		.hpEv = 6,
		.atkEv = 252,
		.defEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[97] =
	{ //Bulky Physical Attacker - Ability_Hidden
		.nature = NATURE_ADAMANT,
		.ivs = 31,
		.hpEv = 6,
		.atkEv = 252,
		.spDefEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[98] =
	{ //Bulky Special Attacker - Ability_Hidden
		.nature = NATURE_MODEST,
		.ivs = 31,
		.hpEv = 252,
		.spdEv = 6,
		.spAtkEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[99] =
	{ //Bulky Special Attacker - Ability_Hidden
		.nature = NATURE_MODEST,
		.ivs = 31,
		.hpEv = 6,
		.defEv = 252,
		.spAtkEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[100] =
	{ //Bulky Special Attacker - Ability_Hidden
		.nature = NATURE_MODEST,
		.ivs = 31,
		.hpEv = 6,
		.spAtkEv = 252,
		.spDefEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[101] =
	{ //Physical Wall - Ability_Hidden
		.nature = NATURE_BOLD,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[102] =
	{ //Physical Wall - Ability_Hidden
		.nature = NATURE_IMPISH,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[103] =
	{ //Special Wall - Ability_Hidden
		.nature = NATURE_CALM,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[104] =
	{ //Special Wall - Ability_Hidden
		.nature = NATURE_CAREFUL,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[105] =
	{ //Mixed Attacker: Attack Based, Less Defense - Ability_Hidden
		.nature = NATURE_LONELY,
		.ivs = 31,
		.atkEv = 128,
		.spdEv = 252,
		.spAtkEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[106] =
	{ //Mixed Attacker: Attack Based, Less Sp. Defense - Ability_Hidden
		.nature = NATURE_NAUGHTY,
		.ivs = 31,
		.atkEv = 128,
		.spdEv = 252,
		.spAtkEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[107] =
	{ //Mixed Attacker: Sp. Attack Based, Less Defense - Ability_Hidden
		.nature = NATURE_MILD,
		.ivs = 31,
		.atkEv = 128,
		.spdEv = 252,
		.spAtkEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[108] =
	{ //Mixed Attacker: Sp. Attack Based, Less Sp. Defense - Ability_Hidden
		.nature = NATURE_RASH,
		.ivs = 31,
		.atkEv = 128,
		.spdEv = 252,
		.spAtkEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[109] =
	{ //Mixed Attacker: Speed Based, Less Defense - Ability_Hidden
		.nature = NATURE_HASTY,
		.ivs = 31,
		.atkEv = 128,
		.spdEv = 252,
		.spAtkEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[110] =
	{ //Mixed Attacker: Speed Based, Less Sp. Defense - Ability_Hidden
		.nature = NATURE_NAIVE,
		.ivs = 31,
		.atkEv = 128,
		.spdEv = 252,
		.spAtkEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[111] =
	{ //Mixed Wall: Defense Based, Less Attack - Ability_Hidden
		.nature = NATURE_BOLD,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 128,
		.spDefEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[112] =
	{ //Mixed Wall: Defense Based, Less Sp. Attack - Ability_Hidden
		.nature = NATURE_IMPISH,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 128,
		.spDefEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[113] =
	{ //Mixed Wall: Sp. Defense Based, Less Attack - Ability_Hidden
		.nature = NATURE_CALM,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 128,
		.spDefEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[114] =
	{ //Mixed Wall: Sp. Defense Based, Less Sp. Attack - Ability_Hidden
		.nature = NATURE_CAREFUL,
		.ivs = 31,
		.hpEv = 252,
		.defEv = 128,
		.spDefEv = 128,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[115] =
	{ //Fast Wall: HP Based, Less Attack - Ability_Hidden
		.nature = NATURE_TIMID,
		.ivs = 31,
		.hpEv = 252,
		.spdEv = 252,
		.spAtkEv = 4,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[116] =
	{ //Fast Wall: HP Based, Less Sp. Attack - Ability_Hidden
		.nature = NATURE_JOLLY,
		.ivs = 31,
		.hpEv = 252,
		.atkEv = 4,
		.spdEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[117] =
	{ //Fast Wall: Defense Based, Less Attack - Ability_Hidden
		.nature = NATURE_TIMID,
		.ivs = 31,
		.hpEv = 4,
		.defEv = 252,
		.spdEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[118] =
	{ //Fast Wall: Defense Based, Less Sp. Attack - Ability_Hidden
		.nature = NATURE_JOLLY,
		.ivs = 31,
		.hpEv = 4,
		.defEv = 252,
		.spdEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[119] =
	{ //Fast Wall: Sp. Defense Based, Less Attack - Ability_Hidden
		.nature = NATURE_TIMID,
		.ivs = 31,
		.hpEv = 4,
		.spdEv = 252,
		.spDefEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[120] =
	{ //Fast Wall: Sp. Defense Based, Less Sp. Attack - Ability_Hidden
		.nature = NATURE_JOLLY,
		.ivs = 31,
		.hpEv = 4,
		.spdEv = 252,
		.spDefEv = 252,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
	[121] =
	{
		.ball = BALL_TYPE_DUSK_BALL,
		.ability = Ability_2,
		.teraType = TYPE_GRASS,
	},
	[122] =
	{
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[123] =
	{
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TERA_TYPE_RANDOM,
	},
    [124] =
	{ //Serious 2nd Rival Fight. Rival's Starter
		.nature = NATURE_SERIOUS,
		.ivs = 25,
		.hpEv = 5,
		.atkEv = 5,
		.defEv = 5,
		.spAtkEv = 5,
		.spDefEv = 5,
		.spdEv = 5,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[125] =
	{ //Hasty 2nd Rival Fight. +Speed -Defense. Rival's Pidgey
		.nature = NATURE_HASTY,
		.ivs = 23,
		.hpEv = 2,
		.atkEv = 2,
		.defEv = 2,
		.spAtkEv = 2,
		.spDefEv = 2,
		.spdEv = 2,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[126] =
	{ //Serious. Champion's Suicune, Raikou
		.nature = NATURE_SERIOUS,
		.ivs = 25,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[127] =
	{ //Serious. Ability 2. Champion's Starter
		.nature = NATURE_SERIOUS,
		.ivs = 25,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[128] =
	{ //Modest +spatk -atk. Champion's Exeggutor
		.nature = NATURE_MODEST,
		.ivs = 23,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[129] =
	{ //Modest +spatk -atk. Hidden Ability. Champion's Alakazam, 
		.nature = NATURE_MODEST,
		.ivs = 23,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[130] =
	{ //Adamant +atk -spatk. Ability 2. Champion's Rhydon, Arcanine
		.nature = NATURE_ADAMANT,
		.ivs = 23,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[131] =
	{ //Hasty +speed -def. Ability Hidden. Champion's Pidgeot
		.nature = NATURE_HASTY,
		.ivs = 23,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[132] =
	{ //Adamant +atk -spatk. Champion's Gyarados
		.nature = NATURE_ADAMANT,
		.ivs = 23,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[133] =
	{ //Adamant +atk -spatk. Ability Hidden. Lance's main Dragonite
		.nature = NATURE_ADAMANT,
		.ivs = 25,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TYPE_NORMAL, 
	},
	[134] =
	{ //Modest. Lance's special Dragonite, Duraludon.
		.nature = NATURE_MODEST,
		.ivs = 23,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA, 
	},
	[135] =
	{ //Careful +spdef -spatk. Ability Hidden. Lance's bulky Dragonite.
		.nature = NATURE_CAREFUL,
		.ivs = 23,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA, 
	},
	[136] =
	{ //Adamant. Ability Hidden. Lance's Gyarados.
		.nature = NATURE_ADAMANT,
		.ivs = 23,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA, 
	},
	[137] =
	{ //Jolly +spe -spatk. Ability Hidden. Lance's Cyclizar.
		.nature = NATURE_JOLLY,
		.ivs = 23,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA, 
	},
	[138] =
	{ //Adamant +atk -spatk. Agatha's Arbok.
		.nature = NATURE_ADAMANT,
		.ivs = 21,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA, 
	},
	[139] =
	{ //Relaxed +def -atk. Ability Hidden. Agatha's Weezing.
		.nature = NATURE_ADAMANT,
		.ivs = 21,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA, 
	},
	[140] =
	{ //Modest. Agatha's Mismagius.
		.nature = NATURE_MODEST,
		.ivs = 21,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA, 
	},
	[141] =
	{ //Jolly. Ability 2. Agatha's Grafaiai.
		.nature = NATURE_JOLLY,
		.ivs = 21,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA, 
	},
	[142] =
	{ //Jolly. Agatha's Crobat, Bruno's Hitmontop.
		.nature = NATURE_JOLLY,
		.ivs = 21,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA, 
	},
	[143] =
	{ //Adamant. Ability 2. Tera Steel. Bruno's Machamp.
		.nature = NATURE_ADAMANT,
		.ivs = 23,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TYPE_STEEL, 
	},
	[144] =
	{ //Adamant. Ability Hidden. Bruno's Onix.
		.nature = NATURE_ADAMANT,
		.ivs = 21,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA, 
	},
	[145] =
	{ //Adamant. Ability 2. Bruno's Hitmonlee, Hitmonchan, Lorelei's Cloyster.
		.nature = NATURE_ADAMANT,
		.ivs = 21,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA, 
	},
	[146] =
	{ //Impish +def -spatk. Bruno's Orthworm.
		.nature = NATURE_IMPISH,
		.ivs = 21,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA, 
	},
	[147] =
	{ //Modest. Lorelei's Lapras.
		.nature = NATURE_MODEST,
		.ivs = 23,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TYPE_DRAGON, 
	},
	[148] =
	{ //Modest. Ability Hidden. Lorelei's Jynx, Slowbro.
		.nature = NATURE_MODEST,
		.ivs = 21,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA, 
	},
	[149] =
	{ //Modest. Ability 2. Lorelei's Farigiraf.
		.nature = NATURE_MODEST,
		.ivs = 21,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA, 
	},
	[150] =
	{ //Calm +spdef -atk. Ability Hidden. Lorelei's Slowking.
		.nature = NATURE_CALM,
		.ivs = 21,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA, 
	},
	[151] =
	{ //Adamant +atk -spatk. Ability Hidden. Champion's Entei
		.nature = NATURE_ADAMANT,
		.ivs = 25,
		.hpEv = 30,
		.atkEv = 30,
		.defEv = 30,
		.spAtkEv = 30,
		.spDefEv = 30,
		.spdEv = 30,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[152] =
	{ //Adamant +atk -spatk. Ability 2. Giovanni's Kangaskhan (Gym)
		.nature = NATURE_ADAMANT,
		.ivs = 21,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[153] =
	{ //Adamant +atk -spatk. Ability 2. Giovanni's Nidoking (Gym)
		.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[154] =
	{ //Jolly. Ability Hidden. Giovanni's Dugtrio (Gym)
		.nature = NATURE_JOLLY,
		.ivs = 19,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[155] =
	{ //Adamant. Ability Hidden. Giovanni's Marowak, Rhydon (Gym), Blaine's Growlithe.
		.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[156] =
	{ //Modest. Ability 2. Blaine's Charizard, Koga's Venonat.
		.nature = NATURE_MODEST,
		.ivs = 19,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[157] =
	{ //Jolly. Ability 2. Giovanni's Persian (Gym), Blaine's Rapidash.
		.nature = NATURE_JOLLY,
		.ivs = 19,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[158] =
	{ //Adamant +atk -spatk. Ability 2. Tera Steel. Blaine's Arcanine
		.nature = NATURE_ADAMANT,
		.ivs = 21,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TYPE_STEEL,
	},
	[159] =
	{ //Serious. Blaine's Magmar.
		.nature = NATURE_SERIOUS,
		.ivs = 19,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[160] =
	{ //Modest. Ability Hidden. Blaine's Ninetales, Koga's Weezing.
		.nature = NATURE_MODEST,
		.ivs = 19,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[161] =
	{ //Modest. Ability 2. Tera Dragon. Koga's Venomoth.
		.nature = NATURE_MODEST,
		.ivs = 21,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TYPE_DRAGON,
	},
	[162] =
	{ //Jolly. Koga's Golbat, Beedrill.
		.nature = NATURE_JOLLY,
		.ivs = 19,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[163] =
	{ //Modest. Ability Hidden. Sabrina's Alakazam.
		.nature = NATURE_MODEST,
		.ivs = 21,
		.hpEv = 69,
		.atkEv = 69,
		.defEv = 69,
		.spAtkEv = 69,
		.spDefEv = 69,
		.spdEv = 69,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[164] =
	{ //Timid. Ability Hidden. Sabrina's Kadabra, Mr.Mime.
		.nature = NATURE_TIMID,
		.ivs = 19,
		.hpEv = 69,
		.atkEv = 69,
		.defEv = 69,
		.spAtkEv = 69,
		.spDefEv = 69,
		.spdEv = 69,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[165] =
	{ //Modest. Ability Hidden. Sabrina's Exeggutor.
		.nature = NATURE_MODEST,
		.ivs = 19,
		.hpEv = 69,
		.atkEv = 69,
		.defEv = 69,
		.spAtkEv = 69,
		.spDefEv = 69,
		.spdEv = 69,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[166] =
	{ //Relaxed. Ability Hidden. Sabrina's Slowbro.
		.nature = NATURE_RELAXED,
		.ivs = 19,
		.hpEv = 69,
		.atkEv = 69,
		.defEv = 69,
		.spAtkEv = 69,
		.spDefEv = 69,
		.spdEv = 69,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[167] =
	{ //Adamant. Ability Hidden. Tera Dark. Koichi's Hitmonlee.
		.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 69,
		.atkEv = 69,
		.defEv = 69,
		.spAtkEv = 69,
		.spDefEv = 69,
		.spdEv = 69,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TYPE_DARK,
	},
	[168] =
	{ //Adamant. Ability 2. Tera Steel. Koichi's Hitmonchan.
		.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 69,
		.atkEv = 69,
		.defEv = 69,
		.spAtkEv = 69,
		.spDefEv = 69,
		.spdEv = 69,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TYPE_STEEL,
	},
	[169] =
	{ //Adamant. Ability Hidden. Koichi's Primeape.
		.nature = NATURE_ADAMANT,
		.ivs = 17,
		.hpEv = 69,
		.atkEv = 69,
		.defEv = 69,
		.spAtkEv = 69,
		.spDefEv = 69,
		.spdEv = 69,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[170] =
	{ //Adamant. Koichi's Poliwrath, Machoke.
		.nature = NATURE_ADAMANT,
		.ivs = 17,
		.hpEv = 69,
		.atkEv = 69,
		.defEv = 69,
		.spAtkEv = 69,
		.spDefEv = 69,
		.spdEv = 69,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[171] =
	{ //Adamant. Ability 2. Koichi's Machop.
		.nature = NATURE_ADAMANT,
		.ivs = 17,
		.hpEv = 69,
		.atkEv = 69,
		.defEv = 69,
		.spAtkEv = 69,
		.spDefEv = 69,
		.spdEv = 69,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[172] =
	{ //Adamant. Ability 2. Giovanni's Kangaskhan (Silph)
		.nature = NATURE_ADAMANT,
		.ivs = 21,
		.hpEv = 69,
		.atkEv = 69,
		.defEv = 69,
		.spAtkEv = 69,
		.spDefEv = 69,
		.spdEv = 69,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[173] =
	{ //Serious. Ability 2. Giovanni's Nidoqueen (Gym).
		.nature = NATURE_SERIOUS,
		.ivs = 19,
		.hpEv = 84,
		.atkEv = 84,
		.defEv = 84,
		.spAtkEv = 84,
		.spDefEv = 84,
		.spdEv = 84,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[174] =
	{ //Serious. Ability 2. Giovanni's Nidoqueen (Silph).
		.nature = NATURE_SERIOUS,
		.ivs = 19,
		.hpEv = 69,
		.atkEv = 69,
		.defEv = 69,
		.spAtkEv = 69,
		.spDefEv = 69,
		.spdEv = 69,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[175] =
	{ //Adamant. Ability 2. Giovanni's Nidoking (Silph)
		.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 69,
		.atkEv = 69,
		.defEv = 69,
		.spAtkEv = 69,
		.spDefEv = 69,
		.spdEv = 69,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[176] =
	{ //Adamant. Ability Hidden. Giovanni's Marowak, Rhyhorn (Silph).
		.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 69,
		.atkEv = 69,
		.defEv = 69,
		.spAtkEv = 69,
		.spDefEv = 69,
		.spdEv = 69,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[177] =
	{ //Jolly. Ability 2. Giovanni's Persian (Silph).
		.nature = NATURE_JOLLY,
		.ivs = 19,
		.hpEv = 69,
		.atkEv = 69,
		.defEv = 69,
		.spAtkEv = 69,
		.spDefEv = 69,
		.spdEv = 69,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[178] =
	{ //Serious. Ability 2. Rival's Starter (Silph)
		.nature = NATURE_SERIOUS,
		.ivs = 25,
		.hpEv = 69,
		.atkEv = 69,
		.defEv = 69,
		.spAtkEv = 69,
		.spDefEv = 69,
		.spdEv = 69,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[179] =
	{ //Adamant. Ability 2. Rival's Growlithe, Rhyhorn (Silph)
		.nature = NATURE_ADAMANT,
		.ivs = 23,
		.hpEv = 69,
		.atkEv = 69,
		.defEv = 69,
		.spAtkEv = 69,
		.spDefEv = 69,
		.spdEv = 69,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[180] =
	{ //Modest. Rival's Exeggutor (Silph)
		.nature = NATURE_MODEST,
		.ivs = 23,
		.hpEv = 69,
		.atkEv = 69,
		.defEv = 69,
		.spAtkEv = 69,
		.spDefEv = 69,
		.spdEv = 69,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[181] =
	{ //Modest. Hidden Ability. Rival's Kadabra (Silph), 
		.nature = NATURE_MODEST,
		.ivs = 23,
		.hpEv = 69,
		.atkEv = 69,
		.defEv = 69,
		.spAtkEv = 69,
		.spDefEv = 69,
		.spdEv = 69,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[182] =
	{ //Hasty. Ability Hidden. Rival's Pidgeot (Silph)
		.nature = NATURE_HASTY,
		.ivs = 23,
		.hpEv = 69,
		.atkEv = 69,
		.defEv = 69,
		.spAtkEv = 69,
		.spDefEv = 69,
		.spdEv = 69,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[183] =
	{ //Adamant. Rival's Gyarados (Silph)
		.nature = NATURE_ADAMANT,
		.ivs = 23,
		.hpEv = 69,
		.atkEv = 69,
		.defEv = 69,
		.spAtkEv = 69,
		.spDefEv = 69,
		.spdEv = 69,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[184] =
	{ //Modest. Erika's Gloom.
		.nature = NATURE_MODEST,
		.ivs = 21,
		.hpEv = 54,
		.atkEv = 54,
		.defEv = 54,
		.spAtkEv = 54,
		.spDefEv = 54,
		.spdEv = 54,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[185] =
	{ //Adamant. Ability Hidden. Erika's Tangela, Victreebel.
		.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 54,
		.atkEv = 54,
		.defEv = 54,
		.spAtkEv = 54,
		.spDefEv = 54,
		.spdEv = 54,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[186] =
	{ //Modest. Erika's Exeggcute.
		.nature = NATURE_MODEST,
		.ivs = 19,
		.hpEv = 54,
		.atkEv = 54,
		.defEv = 54,
		.spAtkEv = 54,
		.spDefEv = 54,
		.spdEv = 54,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[187] =
	{ //Timid. Erika's Ivysaur.
		.nature = NATURE_TIMID,
		.ivs = 19,
		.hpEv = 54,
		.atkEv = 54,
		.defEv = 54,
		.spAtkEv = 54,
		.spDefEv = 54,
		.spdEv = 54,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[188] =
	{ //Modest. Erika's Gloom.
		.nature = NATURE_MODEST,
		.ivs = 21,
		.hpEv = 54,
		.atkEv = 54,
		.defEv = 54,
		.spAtkEv = 54,
		.spDefEv = 54,
		.spdEv = 54,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TYPE_ROCK,
	},
	[189] =
	{ //Adamant. Ability 2. Giovanni's Kangaskhan (Hideout)
		.nature = NATURE_ADAMANT,
		.ivs = 21,
		.hpEv = 54,
		.atkEv = 54,
		.defEv = 54,
		.spAtkEv = 54,
		.spDefEv = 54,
		.spdEv = 54,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TYPE_GHOST,
	},
	[190] =
	{ //Serious. Ability 2. Giovanni's Nidoqueen (Hideout).
		.nature = NATURE_SERIOUS,
		.ivs = 19,
		.hpEv = 54,
		.atkEv = 54,
		.defEv = 54,
		.spAtkEv = 54,
		.spDefEv = 54,
		.spdEv = 54,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[191] =
	{ //Adamant. Ability 2. Giovanni's Nidoking (Hideout)
		.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 54,
		.atkEv = 54,
		.defEv = 54,
		.spAtkEv = 54,
		.spDefEv = 54,
		.spdEv = 54,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[192] =
	{ //Adamant. Ability Hidden. Giovanni's Marowak, Rhyhorn (Hideout).
		.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 54,
		.atkEv = 54,
		.defEv = 54,
		.spAtkEv = 54,
		.spDefEv = 54,
		.spdEv = 54,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[193] =
	{ //Jolly. Ability 2. Giovanni's Persian (Hideout).
		.nature = NATURE_JOLLY,
		.ivs = 19,
		.hpEv = 54,
		.atkEv = 54,
		.defEv = 54,
		.spAtkEv = 54,
		.spDefEv = 54,
		.spdEv = 54,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[194] =
	{ //Serious. Ability 2. Tera Dragon. Rival's Charmeleon (PKMN Tower, SS Anne)
		.nature = NATURE_SERIOUS,
		.ivs = 25,
		.hpEv = 39,
		.atkEv = 39,
		.defEv = 39,
		.spAtkEv = 39,
		.spDefEv = 39,
		.spdEv = 39,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TYPE_DRAGON,
	},
	[195] =
	{ //Modest. Rival's Exeggcute (PKMN Tower)
		.nature = NATURE_MODEST,
		.ivs = 23,
		.hpEv = 39,
		.atkEv = 39,
		.defEv = 39,
		.spAtkEv = 39,
		.spDefEv = 39,
		.spdEv = 39,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[196] =
	{ //Adamant. Ability 2. Rival's Growlithe, Rhyhorn (PKMN Tower)
		.nature = NATURE_ADAMANT,
		.ivs = 23,
		.hpEv = 39,
		.atkEv = 39,
		.defEv = 39,
		.spAtkEv = 39,
		.spDefEv = 39,
		.spdEv = 39,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[197] =
	{ //Modest. Hidden Ability. Rival's Kadabra (PKMN Tower), 
		.nature = NATURE_MODEST,
		.ivs = 23,
		.hpEv = 39,
		.atkEv = 39,
		.defEv = 39,
		.spAtkEv = 39,
		.spDefEv = 39,
		.spdEv = 39,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[198] =
	{ //Hasty. Ability Hidden. Rival's Pidgeotto (PKMN Tower)
		.nature = NATURE_HASTY,
		.ivs = 23,
		.hpEv = 39,
		.atkEv = 39,
		.defEv = 39,
		.spAtkEv = 39,
		.spDefEv = 39,
		.spdEv = 39,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[199] =
	{ //Serious. Ability 2. Tera Rock. Rival's Ivysaur (PKMN Tower, SS Anne)
		.nature = NATURE_SERIOUS,
		.ivs = 25,
		.hpEv = 39,
		.atkEv = 39,
		.defEv = 39,
		.spAtkEv = 39,
		.spDefEv = 39,
		.spdEv = 39,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TYPE_ROCK,
	},
	[200] =
	{ //Adamant. Rival's Gyarados (PKMN Tower)
		.nature = NATURE_ADAMANT,
		.ivs = 23,
		.hpEv = 39,
		.atkEv = 39,
		.defEv = 39,
		.spAtkEv = 39,
		.spDefEv = 39,
		.spdEv = 39,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[201] =
	{ //Serious. Ability 2. Tera Grass. Rival's Wartortle (PKMN Tower, SS Anne)
		.nature = NATURE_SERIOUS,
		.ivs = 25,
		.hpEv = 39,
		.atkEv = 39,
		.defEv = 39,
		.spAtkEv = 39,
		.spDefEv = 39,
		.spdEv = 39,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TYPE_GRASS,
	},
	[202] =
	{ //Serious. Ability 2. Tera Flying. Surge's Raichu.
		.nature = NATURE_SERIOUS,
		.ivs = 21,
		.hpEv = 39,
		.atkEv = 39,
		.defEv = 39,
		.spAtkEv = 39,
		.spDefEv = 39,
		.spdEv = 39,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TYPE_FLYING,
	},
	[203] =
	{ //Serious. Ability 2. Surge's Electabuzz.
		.nature = NATURE_SERIOUS,
		.ivs = 19,
		.hpEv = 39,
		.atkEv = 39,
		.defEv = 39,
		.spAtkEv = 39,
		.spDefEv = 39,
		.spdEv = 39,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[204] =
	{ //Modest. Surge's Magnemite.
		.nature = NATURE_MODEST,
		.ivs = 19,
		.hpEv = 39,
		.atkEv = 39,
		.defEv = 39,
		.spAtkEv = 39,
		.spDefEv = 39,
		.spdEv = 39,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[205] =
	{ //Timid. Ability Hidden. Surge's Voltorb.
		.nature = NATURE_TIMID,
		.ivs = 19,
		.hpEv = 39,
		.atkEv = 39,
		.defEv = 39,
		.spAtkEv = 39,
		.spDefEv = 39,
		.spdEv = 39,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[206] =
	{ //Jolly. Ability 2. Rival's Raticate (SS Anne).
		.nature = NATURE_TIMID,
		.ivs = 23,
		.hpEv = 39,
		.atkEv = 39,
		.defEv = 39,
		.spAtkEv = 39,
		.spDefEv = 39,
		.spdEv = 39,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[207] =
	{ //Serious. Ability 2. Tera Dragon. Rival's Charmeleon (Cerulean)
		.nature = NATURE_SERIOUS,
		.ivs = 25,
		.hpEv = 24,
		.atkEv = 24,
		.defEv = 24,
		.spAtkEv = 24,
		.spDefEv = 24,
		.spdEv = 24,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TYPE_DRAGON,
	},
	[208] =
	{ //Jolly. Ability 2. Rival's Rattata (Cerulean).
		.nature = NATURE_TIMID,
		.ivs = 23,
		.hpEv = 24,
		.atkEv = 24,
		.defEv = 24,
		.spAtkEv = 24,
		.spDefEv = 24,
		.spdEv = 24,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[209] =
	{ //Modest. Hidden Ability. Rival's Kadabra (Cerulean), 
		.nature = NATURE_MODEST,
		.ivs = 23,
		.hpEv = 24,
		.atkEv = 24,
		.defEv = 24,
		.spAtkEv = 24,
		.spDefEv = 24,
		.spdEv = 24,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[210] =
	{ //Hasty. Ability Hidden. Rival's Pidgey (Cerulean)
		.nature = NATURE_HASTY,
		.ivs = 23,
		.hpEv = 24,
		.atkEv = 24,
		.defEv = 24,
		.spAtkEv = 24,
		.spDefEv = 24,
		.spdEv = 24,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[211] =
	{ //Serious. Ability 2. Tera Rock. Rival's Ivysaur (Cerulean)
		.nature = NATURE_SERIOUS,
		.ivs = 25,
		.hpEv = 24,
		.atkEv = 24,
		.defEv = 24,
		.spAtkEv = 24,
		.spDefEv = 24,
		.spdEv = 24,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TYPE_ROCK,
	},
	[212] =
	{ //Serious. Ability 2. Tera Grass. Rival's Wartortle (Cerulean)
		.nature = NATURE_SERIOUS,
		.ivs = 25,
		.hpEv = 24,
		.atkEv = 24,
		.defEv = 24,
		.spAtkEv = 24,
		.spDefEv = 24,
		.spdEv = 24,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TYPE_GRASS,
	},
	[213] =
	{ //Serious. Ability Hidden. Tera Poison. Misty's Starmie
		.nature = NATURE_SERIOUS,
		.ivs = 21,
		.hpEv = 24,
		.atkEv = 24,
		.defEv = 24,
		.spAtkEv = 24,
		.spDefEv = 24,
		.spdEv = 24,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TYPE_POISON,
	},
	[214] =
	{ //Quiet +spatk -spe. Ability 2. Misty's Psyduck.
		.nature = NATURE_QUIET,
		.ivs = 19,
		.hpEv = 24,
		.atkEv = 24,
		.defEv = 24,
		.spAtkEv = 24,
		.spDefEv = 24,
		.spdEv = 24,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[215] =
	{ //Serious. Ability Hidden. Misty's Goldeen.
		.nature = NATURE_SERIOUS,
		.ivs = 19,
		.hpEv = 24,
		.atkEv = 24,
		.defEv = 24,
		.spAtkEv = 24,
		.spDefEv = 24,
		.spdEv = 24,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[216] =
	{ //Serious. Ability 2. Misty's Staryu.
		.nature = NATURE_SERIOUS,
		.ivs = 19,
		.hpEv = 24,
		.atkEv = 24,
		.defEv = 24,
		.spAtkEv = 24,
		.spDefEv = 24,
		.spdEv = 24,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[217] =
	{ //Serious. Miguel's Magnemite.
		.nature = NATURE_SERIOUS,
		.ivs = 17,
		.hpEv = 24,
		.atkEv = 24,
		.defEv = 24,
		.spAtkEv = 24,
		.spDefEv = 24,
		.spdEv = 24,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TYPE_ELECTRIC,
	},
	[218] =
	{ //Serious. Miguel's other Pokemon.
		.nature = NATURE_SERIOUS,
		.ivs = 15,
		.hpEv = 24,
		.atkEv = 24,
		.defEv = 24,
		.spAtkEv = 24,
		.spDefEv = 24,
		.spdEv = 24,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[219] =
	{ //Adamant. Ability 2. Tera Rock. Brock's Onix.
		.nature = NATURE_ADAMANT,
		.ivs = 21,
		.hpEv = 24,
		.atkEv = 24,
		.defEv = 24,
		.spAtkEv = 24,
		.spDefEv = 24,
		.spdEv = 24,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TYPE_ROCK,
	},
	[220] =
	{ //Jolly. Ability 2. Brock's Sandshrew.
		.nature = NATURE_JOLLY,
		.ivs = 19,
		.hpEv = 24,
		.atkEv = 24,
		.defEv = 24,
		.spAtkEv = 24,
		.spDefEv = 24,
		.spdEv = 24,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[221] =
	{ //Adamant. Ability 2. Brock's Geodude.
		.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 24,
		.atkEv = 24,
		.defEv = 24,
		.spAtkEv = 24,
		.spDefEv = 24,
		.spdEv = 24,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[222] =
	{ //Serious. Ability 2. Rival's Starters (Oak's Lab).
		.nature = NATURE_SERIOUS,
		.ivs = 25,
		.hpEv = 0,
		.atkEv = 0,
		.defEv = 0,
		.spAtkEv = 0,
		.spDefEv = 0,
		.spdEv = 0,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[223] =
	{ //Serious. 15 ivs, 10 evs. Sammy's Butterfree.
		.nature = NATURE_SERIOUS,
		.ivs = 15,
		.hpEv = 10,
		.atkEv = 10,
		.defEv = 10,
		.spAtkEv = 10,
		.spDefEv = 10,
		.spdEv = 10,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[224] =
	{ //Serious. 10 ivs, 0 evs. Viridian Forest.
		.nature = NATURE_SERIOUS,
		.ivs = 10,
		.hpEv = 0,
		.atkEv = 0,
		.defEv = 0,
		.spAtkEv = 0,
		.spDefEv = 0,
		.spdEv = 0,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[225] =
	{ //Serious. 10 ivs, 10 evs. Route 3.
		.nature = NATURE_SERIOUS,
		.ivs = 10,
		.hpEv = 10,
		.atkEv = 10,
		.defEv = 10,
		.spAtkEv = 10,
		.spDefEv = 10,
		.spdEv = 10,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[226] =
	{ //Serious. 10 ivs, 10 evs. Robin's Jigglypuff on Route 3.
		.nature = NATURE_SERIOUS,
		.ivs = 10,
		.hpEv = 10,
		.atkEv = 10,
		.defEv = 10,
		.spAtkEv = 10,
		.spDefEv = 10,
		.spdEv = 10,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TYPE_GHOST,
	},
	[227] =
	{ //Serious. 19 ivs, 20 evs. Ability Hidden. Haley's Weepinbell on Route 25.
		.nature = NATURE_SERIOUS,
		.ivs = 19,
		.hpEv = 20,
		.atkEv = 20,
		.defEv = 20,
		.spAtkEv = 20,
		.spDefEv = 20,
		.spdEv = 20,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TYPE_ROCK,
	},
	[228] =
	{ //Modest. 17 ivs, 15 evs. Ability 2. Haley's Horsea on Route 25.
		.nature = NATURE_MODEST,
		.ivs = 17,
		.hpEv = 15,
		.atkEv = 15,
		.defEv = 15,
		.spAtkEv = 15,
		.spDefEv = 15,
		.spdEv = 15,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[229] =
	{ //Timid. 17 ivs, 15 evs. Ability Hidden. Haley's Vulpix on Route 25.
		.nature = NATURE_TIMID,
		.ivs = 17,
		.hpEv = 15,
		.atkEv = 15,
		.defEv = 15,
		.spAtkEv = 15,
		.spDefEv = 15,
		.spdEv = 15,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[230] =
	{ //Serious. 17 ivs, 15 evs. Haley's Pikachu on Route 25, all of Chris' mid Mons. (Alot of the good trainers)
		.nature = NATURE_SERIOUS,
		.ivs = 17,
		.hpEv = 15,
		.atkEv = 15,
		.defEv = 15,
		.spAtkEv = 15,
		.spDefEv = 15,
		.spdEv = 15,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[231] =
	{ //Serious. 19 ivs, 20 evs. Ricky's Squirtle on Route 6.
		.nature = NATURE_SERIOUS,
		.ivs = 19,
		.hpEv = 20,
		.atkEv = 20,
		.defEv = 20,
		.spAtkEv = 20,
		.spDefEv = 20,
		.spdEv = 20,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TYPE_STEEL,
	},
	[232] =
	{ //Adamant. 17 ivs, 15 evs. Ricky's Paras on Route 6.
		.nature = NATURE_ADAMANT,
		.ivs = 17,
		.hpEv = 15,
		.atkEv = 15,
		.defEv = 15,
		.spAtkEv = 15,
		.spDefEv = 15,
		.spdEv = 15,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[233] =
	{ //Jolly. 17 ivs, 15 evs. Ability 2. Ricky's Raticate and Sandshrew on Route 6.
		.nature = NATURE_JOLLY,
		.ivs = 17,
		.hpEv = 15,
		.atkEv = 15,
		.defEv = 15,
		.spAtkEv = 15,
		.spDefEv = 15,
		.spdEv = 15,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[234] =
	{ //Adamant. 19 ivs, 20 evs. Ability Hidden. Thomas's Growlithe on SS Anne.
		.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 20,
		.atkEv = 20,
		.defEv = 20,
		.spAtkEv = 20,
		.spDefEv = 20,
		.spdEv = 20,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TYPE_WATER,
	},
	[235] =
	{ //Adamant. 17 ivs, 15 evs. Ability 2. Thomas's Geodude on SS Anne.
		.nature = NATURE_ADAMANT,
		.ivs = 17,
		.hpEv = 15,
		.atkEv = 15,
		.defEv = 15,
		.spAtkEv = 15,
		.spDefEv = 15,
		.spdEv = 15,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[236] =
	{ //Modest. 17 ivs, 15 evs. Ability 2. Thomas's Venonat on SS Anne.
		.nature = NATURE_MODEST,
		.ivs = 17,
		.hpEv = 15,
		.atkEv = 15,
		.defEv = 15,
		.spAtkEv = 15,
		.spDefEv = 15,
		.spdEv = 15,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[237] =
	{ //Jolly. 17 ivs, 15 evs. Ability 2. Thomas's Meowth on SS Anne, Dirk's Diglett.
		.nature = NATURE_JOLLY,
		.ivs = 17,
		.hpEv = 15,
		.atkEv = 15,
		.defEv = 15,
		.spAtkEv = 15,
		.spDefEv = 15,
		.spdEv = 15,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[238] =
	{ //Serious. 19 ivs, 20 evs. Ability 2. Dirk's Electabuzz on Route 11.
		.nature = NATURE_SERIOUS,
		.ivs = 19,
		.hpEv = 20,
		.atkEv = 20,
		.defEv = 20,
		.spAtkEv = 20,
		.spDefEv = 20,
		.spdEv = 20,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TYPE_FLYING,
	},
	[239] =
	{ //Modest. 17 ivs, 15 evs. Ability Hidden. Dirk's Drowzee on Route 11.
		.nature = NATURE_MODEST,
		.ivs = 17,
		.hpEv = 15,
		.atkEv = 15,
		.defEv = 15,
		.spAtkEv = 15,
		.spDefEv = 15,
		.spdEv = 15,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[240] =
	{ //Adamant. 17 ivs, 15 evs. Ability Hidden. Dirk's Mankey on Route 11.
		.nature = NATURE_ADAMANT,
		.ivs = 17,
		.hpEv = 15,
		.atkEv = 15,
		.defEv = 15,
		.spAtkEv = 15,
		.spDefEv = 15,
		.spdEv = 15,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[241] =
	{ //Serious. 19 ivs, 20 evs. Chris's Charmander on Route 9.
		.nature = NATURE_SERIOUS,
		.ivs = 19,
		.hpEv = 20,
		.atkEv = 20,
		.defEv = 20,
		.spAtkEv = 20,
		.spDefEv = 20,
		.spdEv = 20,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TYPE_STELLAR,
	},
	[242] =
	{ //Adamant. 19 ivs, 20 evs. Ashton's Cubone in Rock Tunnel.
		.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 20,
		.atkEv = 20,
		.defEv = 20,
		.spAtkEv = 20,
		.spDefEv = 20,
		.spdEv = 20,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TYPE_WATER,
	},
	[243] =
	{ //Serious. 17 ivs, 15 evs. Ability Hidden. Ashton's Slowpoke in Rock Tunnel.
		.nature = NATURE_SERIOUS,
		.ivs = 17,
		.hpEv = 15,
		.atkEv = 15,
		.defEv = 15,
		.spAtkEv = 15,
		.spDefEv = 15,
		.spdEv = 15,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[244] =
	{ //Serious. 17 ivs, 15 evs. Ability 2. Ashton's Jigglypuff in Rock Tunnel.
		.nature = NATURE_SERIOUS,
		.ivs = 17,
		.hpEv = 15,
		.atkEv = 15,
		.defEv = 15,
		.spAtkEv = 15,
		.spDefEv = 15,
		.spdEv = 15,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[245] =
	{ //Modest. 19 ivs, 20 evs. Emilia's Haunter in Pokemon Tower.
		.nature = NATURE_MODEST,
		.ivs = 19,
		.hpEv = 20,
		.atkEv = 20,
		.defEv = 20,
		.spAtkEv = 20,
		.spDefEv = 20,
		.spdEv = 20,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TYPE_ELECTRIC,
	},
	[246] =
	{ //Adamant. 19 ivs, 20 evs. Ability Hidden. Tera Ghost. Glenn's Eevee on Route 8.
		.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 20,
		.atkEv = 20,
		.defEv = 20,
		.spAtkEv = 20,
		.spDefEv = 20,
		.spdEv = 20,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TYPE_GHOST,
	},
	[247] =
	{ //Modest. 19 ivs, 30 evs. Ability 2. Tera Flying. Luca's Electrode on Route 12.
		.nature = NATURE_MODEST,
		.ivs = 19,
		.hpEv = 30,
		.atkEv = 30,
		.defEv = 30,
		.spAtkEv = 30,
		.spDefEv = 30,
		.spdEv = 30,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TYPE_FLYING,
	},
	[248] =
	{ //Serious. 17 ivs, 25 evs. Luca's Rhyhorn, Haunter on Route 12.
		.nature = NATURE_SERIOUS,
		.ivs = 17,
		.hpEv = 25,
		.atkEv = 25,
		.defEv = 25,
		.spAtkEv = 25,
		.spDefEv = 25,
		.spdEv = 25,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = DONT_TERA,
	},
	[249] =
	{ //Serious. 17 ivs, 25 evs. Ability 2. Luca's Machoke on Route 12.
		.nature = NATURE_SERIOUS,
		.ivs = 17,
		.hpEv = 25,
		.atkEv = 25,
		.defEv = 25,
		.spAtkEv = 25,
		.spDefEv = 25,
		.spdEv = 25,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = DONT_TERA,
	},
	[250] =
	{ //Serious. 17 ivs, 25 evs. Ability Hidden. Luca's Kadabra on Route 12.
		.nature = NATURE_SERIOUS,
		.ivs = 17,
		.hpEv = 25,
		.atkEv = 25,
		.defEv = 25,
		.spAtkEv = 25,
		.spDefEv = 25,
		.spdEv = 25,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = DONT_TERA,
	},
	[251] =
	{ //Serious. 19 ivs, 30 evs. Tera Dragon. Alma's Seadra on Route 13.
		.nature = NATURE_SERIOUS,
		.ivs = 19,
		.hpEv = 30,
		.atkEv = 30,
		.defEv = 30,
		.spAtkEv = 30,
		.spDefEv = 30,
		.spdEv = 30,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_1,
		.teraType = TYPE_DRAGON,
	},
	[252] =
	{ //Adamant. 19 ivs, 30 evs. Ability 2. Tera Ghost. Marlon's Dodrio on Route 14.
		.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 30,
		.atkEv = 30,
		.defEv = 30,
		.spAtkEv = 30,
		.spDefEv = 30,
		.spdEv = 30,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TYPE_FLYING,
	},
	[253] =
	{ //Adamant. 19 ivs, 30 evs. Ability 2. Tera Rock. Ron and Mya's Hitmons on Route 15.
		.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 30,
		.atkEv = 30,
		.defEv = 30,
		.spAtkEv = 30,
		.spDefEv = 30,
		.spdEv = 30,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TYPE_ROCK,
	},
	[254] =
	{ //Adamant. 19 ivs, 30 evs. Ability 2. Tera Dark. Isaiah's Machoke on Route 17.
		.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 30,
		.atkEv = 30,
		.defEv = 30,
		.spAtkEv = 30,
		.spDefEv = 30,
		.spdEv = 30,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_2,
		.teraType = TYPE_DARK,
	},
	[255] =
	{ //Adamant. 19 ivs, 30 evs. Ability Hidden. Tera Grass. Lea and Jed's Rapidash on Route 16.
		.nature = NATURE_ADAMANT,
		.ivs = 19,
		.hpEv = 30,
		.atkEv = 30,
		.defEv = 30,
		.spAtkEv = 30,
		.spDefEv = 30,
		.spdEv = 30,
		.ball = TRAINER_EV_CLASS_BALL,
		.ability = Ability_Hidden,
		.teraType = TYPE_GRASS,
	},
	// [256] = //2
	// { //Modest. 19 ivs, 30 evs. Ability Hidden. Tera Ghost. Lea and Jed's Ninetales on Route 16.
	// 	.nature = NATURE_MODEST,
	// 	.ivs = 19,
	// 	.hpEv = 30,
	// 	.atkEv = 30,
	// 	.defEv = 30,
	// 	.spAtkEv = 30,
	// 	.spDefEv = 30,
	// 	.spdEv = 30,
	// 	.ball = TRAINER_EV_CLASS_BALL,
	// 	.ability = Ability_Hidden,
	// 	.teraType = TYPE_GHOST,
	// },
	// [257] = //3
	// { //Adamant. 19 ivs, 30 evs. Axle's Gyarados on Route 19.
	// 	.nature = NATURE_ADAMANT,
	// 	.ivs = 19,
	// 	.hpEv = 30,
	// 	.atkEv = 30,
	// 	.defEv = 30,
	// 	.spAtkEv = 30,
	// 	.spDefEv = 30,
	// 	.spdEv = 30,
	// 	.ball = TRAINER_EV_CLASS_BALL,
	// 	.ability = Ability_1,
	// 	.teraType = DONT_TERA,
	// },
	// [258] = //4
	// { //Adamant. 19 ivs, 30 evs. Tera Ghost. Mark's Lickitung on Route 10.
	// 	.nature = NATURE_ADAMANT,
	// 	.ivs = 19,
	// 	.hpEv = 30,
	// 	.atkEv = 30,
	// 	.defEv = 30,
	// 	.spAtkEv = 30,
	// 	.spDefEv = 30,
	// 	.spdEv = 30,
	// 	.ball = TRAINER_EV_CLASS_BALL,
	// 	.ability = Ability_Hidden,
	// 	.teraType = TYPE_GHOST,
	// },
	// [259] = //5
	// { //Adamant. 19 ivs, 30 evs. Tera Electric. Ivan's Electivire in Cinnabar Lab.
	// 	.nature = NATURE_ADAMANT,
	// 	.ivs = 19,
	// 	.hpEv = 30,
	// 	.atkEv = 30,
	// 	.defEv = 30,
	// 	.spAtkEv = 30,
	// 	.spDefEv = 30,
	// 	.spdEv = 30,
	// 	.ball = TRAINER_EV_CLASS_BALL,
	// 	.ability = Ability_Hidden,
	// 	.teraType = TYPE_ELECTRIC,
	// },
	// [260] = //6
	// { //Modest. 19 ivs, 30 evs. Tera Fairy. Claire's Clefable on Kindle Road.
	// 	.nature = NATURE_MODEST,
	// 	.ivs = 19,
	// 	.hpEv = 30,
	// 	.atkEv = 30,
	// 	.defEv = 30,
	// 	.spAtkEv = 30,
	// 	.spDefEv = 30,
	// 	.spdEv = 30,
	// 	.ball = TRAINER_EV_CLASS_BALL,
	// 	.ability = Ability_2,
	// 	.teraType = TYPE_FAIRY,
	// },
	// [261] = //7
	// { //Serious. 19 ivs, 30 evs. Logan's Charizard at Mt. Ember.
	// 	.nature = NATURE_SERIOUS,
	// 	.ivs = 19,
	// 	.hpEv = 30,
	// 	.atkEv = 30,
	// 	.defEv = 30,
	// 	.spAtkEv = 30,
	// 	.spDefEv = 30,
	// 	.spdEv = 30,
	// 	.ball = TRAINER_EV_CLASS_BALL,
	// 	.ability = Ability_1,
	// 	.teraType = DONT_TERA,
	// },
	// [262] = //8
	// { //Serious. 19 ivs, 30 evs. Tera Dark. Paxton's Muk and Weezing on Three Island.
	// 	.nature = NATURE_SERIOUS,
	// 	.ivs = 19,
	// 	.hpEv = 30,
	// 	.atkEv = 30,
	// 	.defEv = 30,
	// 	.spAtkEv = 30,
	// 	.spDefEv = 30,
	// 	.spdEv = 30,
	// 	.ball = TRAINER_EV_CLASS_BALL,
	// 	.ability = Ability_Hidden,
	// 	.teraType = TYPE_DARK,
	// },
	// [263] = //9
	// { //Adamant. 19 ivs, 30 evs. Tera Water. Tisha's Kingler on Bond Bridge.
	// 	.nature = NATURE_ADAMANT,
	// 	.ivs = 19,
	// 	.hpEv = 30,
	// 	.atkEv = 30,
	// 	.defEv = 30,
	// 	.spAtkEv = 30,
	// 	.spDefEv = 30,
	// 	.spdEv = 30,
	// 	.ball = TRAINER_EV_CLASS_BALL,
	// 	.ability = Ability_Hidden,
	// 	.teraType = TYPE_WATER,
	// },
	// [264] = //10
	// // { //Adamant. 19 ivs, 50 evs. Tera Poison. Ray and Tyra's Nidoking in Victory Road.
	// // 	.nature = NATURE_ADAMANT,
	// // 	.ivs = 19,
	// // 	.hpEv = 50,
	// // 	.atkEv = 50,
	// // 	.defEv = 50,
	// // 	.spAtkEv = 50,
	// // 	.spDefEv = 50,
	// // 	.spdEv = 50,
	// // 	.ball = TRAINER_EV_CLASS_BALL,
	// // 	.ability = Ability_1,
	// // 	.teraType = TYPE_POISON,
	// },
	// [265] = //11
	// { //Modest. 19 ivs, 50 evs. Tera Flying. Ray and Tyra's Nidoqueen in Victory Road.
	// 	.nature = NATURE_MODEST,
	// 	.ivs = 19,
	// 	.hpEv = 50,
	// 	.atkEv = 50,
	// 	.defEv = 50,
	// 	.spAtkEv = 50,
	// 	.spDefEv = 50,
	// 	.spdEv = 50,
	// 	.ball = TRAINER_EV_CLASS_BALL,
	// 	.ability = Ability_2,
	// 	.teraType = TYPE_FLYING,
	// },
	// [266] = //12
	// { //Victory Road Trainer Mons.
	// 	.nature = NATURE_SERIOUS,
	// 	.ivs = 17,
	// 	.hpEv = 45,
	// 	.atkEv = 45,
	// 	.defEv = 45,
	// 	.spAtkEv = 45,
	// 	.spDefEv = 45,
	// 	.spdEv = 45,
	// 	.ball = TRAINER_EV_CLASS_BALL,
	// 	.ability = Ability_1,
	// 	.teraType = DONT_TERA,
	// },
	// [267] = //13
	// { //Victory Road Trainer Mons Ability 2.
	// 	.nature = NATURE_SERIOUS,
	// 	.ivs = 17,
	// 	.hpEv = 45,
	// 	.atkEv = 45,
	// 	.defEv = 45,
	// 	.spAtkEv = 45,
	// 	.spDefEv = 45,
	// 	.spdEv = 45,
	// 	.ball = TRAINER_EV_CLASS_BALL,
	// 	.ability = Ability_2,
	// 	.teraType = DONT_TERA,
	// },
	// [268] = //14
	// { //Victory Road Trainer Mons Ability Hidden.
	// 	.nature = NATURE_SERIOUS,
	// 	.ivs = 17,
	// 	.hpEv = 45,
	// 	.atkEv = 45,
	// 	.defEv = 45,
	// 	.spAtkEv = 45,
	// 	.spDefEv = 45,
	// 	.spdEv = 45,
	// 	.ball = TRAINER_EV_CLASS_BALL,
	// 	.ability = Ability_Hidden,
	// 	.teraType = DONT_TERA,
	// },
	// [269] = //15
	// { //Adamant. Ability Hidden, Tera Normal. Dawson's Lickilicky on Victory Road.
	// 	.nature = NATURE_ADAMANT,
	// 	.ivs = 19,
	// 	.hpEv = 50,
	// 	.atkEv = 50,
	// 	.defEv = 50,
	// 	.spAtkEv = 50,
	// 	.spDefEv = 50,
	// 	.spdEv = 50,
	// 	.ball = TRAINER_EV_CLASS_BALL,
	// 	.ability = Ability_Hidden,
	// 	.teraType = TYPE_NORMAL,
	// },
	// [270] = //16
	// { //Adamant. Ability Hidden, Nelson's Aerodactyl on Victory Road.
	// 	.nature = NATURE_ADAMANT,
	// 	.ivs = 19,
	// 	.hpEv = 50,
	// 	.atkEv = 50,
	// 	.defEv = 50,
	// 	.spAtkEv = 50,
	// 	.spDefEv = 50,
	// 	.spdEv = 50,
	// 	.ball = TRAINER_EV_CLASS_BALL,
	// 	.ability = Ability_Hidden,
	// 	.teraType = DONT_TERA,
	// },
};

#endif

const u8 gBaseIVsByTrainerClass[NUM_TRAINER_CLASSES] =
{
	[CLASS_YOUNGSTER] = 5,
	[CLASS_BUG_CATCHER] = 1,
	[CLASS_LASS] =  5,
	[CLASS_SAILOR] = 10,
	[CLASS_CAMPER] = 5,
	[CLASS_PICNICKER] =  5,
	[CLASS_POKEMANIAC] = 10,
	[CLASS_SUPER_NERD] = 15,
	[CLASS_HIKER] = 10,
	[CLASS_BIKER] = 10,
	[CLASS_BURGLAR] = 10,
	[CLASS_ENGINEER] = 10,
	[CLASS_FISHERMAN] = 10,
	[CLASS_SWIMMER_M] = 10,
	[CLASS_CUE_BALL] = 10,
	[CLASS_GAMBLER] = 10,
	[CLASS_BEAUTY] =  10,
	[CLASS_SWIMMER_F] =  10,
	[CLASS_PSYCHIC] = 15,
	[CLASS_ROCKER] = 10,
	[CLASS_JUGGLER] = 10,
	[CLASS_TAMER] = 16,
	[CLASS_BIRD_KEEPER] = 10,
	[CLASS_BLACK_BELT] = 15,
	[CLASS_RIVAL] = 25,
	[CLASS_SCIENTIST] = 15,
	[CLASS_BOSS] = 21,
	[CLASS_LEADER] = 21,
	[CLASS_TEAM_ROCKET] = 15,
	[CLASS_COOLTRAINER] = 25,
	[CLASS_ELITE_4] = 23,
	[CLASS_GENTLEMAN] = 15,
	[CLASS_RIVAL_2] = 25, //31
	[CLASS_CHAMPION] = 25,
	[CLASS_CHANNELER] = 10,
	[CLASS_TWINS] =  5,
	[CLASS_COOL_COUPLE] = 18,
	[CLASS_YOUNG_COUPLE] = 15,
	[CLASS_CRUSH_KIN] = 15,
	[CLASS_SIS_AND_BRO] =  10,
	[CLASS_PKMN_PROF] = 23,
	[CLASS_PLAYER] = 25,
	[CLASS_CRUSH_GIRL] = 15,
	[CLASS_TUBER] = 5,
	[CLASS_PKMN_BREEDER] = 15,
	[CLASS_PKMN_RANGER] = 16,
	[CLASS_AROMA_LADY] =  10,
	[CLASS_RUIN_MANIAC] = 10,
	[CLASS_LADY] =  16,
	[CLASS_PAINTER] =  10,
};
